spring:
  application.name: TransactionManagement
  datasource:
    url: jdbc:mysql://localhost:3306/transaction_management
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    h2.console.enabled: false
